Updated PluginChecker
- Now plugin status is stored on enables, and not queried every time methods are used
- Fixed NoSuchMethodError due to not checking whether Parties is enabled