Updated ArmorStandMechanic
Disabled marker tag for 1.8. due to NoSuchMethodError
Armor stand intances in 1.8 are protected from damage though event handling, not invulnerability
Protected armor stand intances from player interactions