Target Improvements
- Linear and Single targets now they check for a collision with the actual hitbox of the entity, not just their center point
- Linear and Single targets now uses the disguise hitbox, if the entity is disguised, and the disguise is set to modify their hitbox
- Area target now gives priority to the nearest entities if "Random" is false
- Fixed caster sometimes being included in the targets even if "Include Caster" was false
- Fixed NoSuchMethodError under 1.13